; CODE SCANNER List of 379 non-native Globals
; extracted from: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Huawei Hacker Toolkit.au3
; on 2016-02-22, at 08:53:23


; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Huawei Hacker Toolkit.au3
Global $sAppName	 ; line 29
Global $sAppVersion	 ; line 30
Global $sAppPublisher	 ; line 31
Global $sAppURL	 ; line 32
Global $vPrivateKey	 ; line 34
Global $DBT_DEVNODES_CHANGED	 ; line 36
Global $dSignature1	 ; line 38
Global $tagHEADER	 ; line 39
Global $dSignature2	 ; line 53
Global $sTitle	 ; line 55
Global $sDeviceState	 ; line 56
Global $sManufacturer	 ; line 56
Global $sModelNumber	 ; line 56
Global $sDeviceID	 ; line 56
Global $bRootAccess	 ; line 56

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Include\Busy.au3
Global $BSY_SIZE	 ; line 20
Global $BSY_MAINWIN	 ; line 20
Global $BSY_PARWIN	 ; line 20
Global $BSY_GIFOBJ	 ; line 20
Global $BSY_STATUSTEXT	 ; line 20
Global $BSY_STATUSBAR	 ; line 20
Global $BSY_SCREENWIN	 ; line 20
Global $BSY_THEME_DIR	 ; line 20
Global $BSY_THEME_BGCOLOR	 ; line 20
Global $BSY_THEME_TEXT	 ; line 20
Global $BSY_THEME_BAR	 ; line 20
Global $BSY_THEME_BGBAR	 ; line 20
Global $BSY_THEME_SCREEN	 ; line 20
Global $BSY_THEME_GIF	 ; line 20
Global $BSY_THEME_CORNERS	 ; line 20
Global $BUSY_SCREEN	 ; line 36
Global $BUSY_PROGRESS	 ; line 36
Global $BUSY_FULLSCREEN	 ; line 36
Global $BUSY_TOPMOST	 ; line 36
Global $g_aBsy_Info[$BSY_SIZE]	 ; line 41
Global $g_aBsy_GIFs	 ; line 41
Global $g_aBsy_GIFs	 ; line 41
Global $g_hBsy_GIFThread	 ; line 41
Global $g_iBsy_Transparency	 ; line 41
Global $g_tBsy_CurrentFrame	 ; line 41

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Include\CRC.au3
Global $_CRC32_CodeBuffer	 ; line 10
Global $_CRC32_CodeBufferMemory	 ; line 10
Global $_CRC16_CodeBuffer	 ; line 11
Global $_CRC16_CodeBufferMemory	 ; line 11

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\MCFinclude.au3
Global $MCFinclude	 ; line 138
Global $CCkeytype	 ; line 139
Global $CCkey[2]	 ; line 140

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Include\Registration.au3
Global $VALID_CHARS	 ; line 12
Global $idSerialNumberInput	 ; line 14
Global $idRegisterButton	 ; line 14
Global $__vPrivateKey	 ; line 14

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\Include\AndroidConstants.au3
Global $INSTALL_SUCCEEDED	 ; line 12
Global $INSTALL_FAILED_ALREADY_EXISTS	 ; line 13
Global $INSTALL_FAILED_INVALID_APK	 ; line 14
Global $INSTALL_FAILED_INVALID_URI	 ; line 15
Global $INSTALL_FAILED_INSUFFICIENT_STORAGE	 ; line 16
Global $INSTALL_FAILED_DUPLICATE_PACKAGE	 ; line 17
Global $INSTALL_FAILED_NO_SHARED_USER	 ; line 18
Global $INSTALL_FAILED_UPDATE_INCOMPATIBLE	 ; line 19
Global $INSTALL_FAILED_SHARED_USER_INCOMPATIBLE	 ; line 20
Global $INSTALL_FAILED_MISSING_SHARED_LIBRARY	 ; line 21
Global $INSTALL_FAILED_REPLACE_COULDNT_DELETE	 ; line 22
Global $INSTALL_FAILED_DEXOPT	 ; line 23
Global $INSTALL_FAILED_OLDER_SDK	 ; line 24
Global $INSTALL_FAILED_CONFLICTING_PROVIDER	 ; line 25
Global $INSTALL_FAILED_NEWER_SDK	 ; line 26
Global $INSTALL_FAILED_TEST_ONLY	 ; line 27
Global $INSTALL_FAILED_CPU_ABI_INCOMPATIBLE	 ; line 28
Global $INSTALL_FAILED_MISSING_FEATURE	 ; line 29
Global $INSTALL_FAILED_CONTAINER_ERROR	 ; line 30
Global $INSTALL_FAILED_INVALID_INSTALL_LOCATION	 ; line 31
Global $INSTALL_FAILED_MEDIA_UNAVAILABLE	 ; line 32
Global $INSTALL_FAILED_VERIFICATION_TIMEOUT	 ; line 33
Global $INSTALL_FAILED_VERIFICATION_FAILURE	 ; line 34
Global $INSTALL_FAILED_PACKAGE_CHANGED	 ; line 35
Global $INSTALL_FAILED_UID_CHANGED	 ; line 36
Global $INSTALL_FAILED_VERSION_DOWNGRADE	 ; line 37
Global $INSTALL_FAILED_INTERNAL_ERROR	 ; line 38
Global $INSTALL_FAILED_USER_RESTRICTED	 ; line 39
Global $KEYCODE_UNKNOWN	 ; line 41
Global $KEYCODE_SOFT_LEFT	 ; line 42
Global $KEYCODE_SOFT_RIGHT	 ; line 43
Global $KEYCODE_HOME	 ; line 44
Global $KEYCODE_BACK	 ; line 45
Global $KEYCODE_CALL	 ; line 46
Global $KEYCODE_ENDCALL	 ; line 47
Global $KEYCODE_0	 ; line 48
Global $KEYCODE_1	 ; line 49
Global $KEYCODE_2	 ; line 50
Global $KEYCODE_3	 ; line 51
Global $KEYCODE_4	 ; line 52
Global $KEYCODE_5	 ; line 53
Global $KEYCODE_6	 ; line 54
Global $KEYCODE_7	 ; line 55
Global $KEYCODE_8	 ; line 56
Global $KEYCODE_9	 ; line 57
Global $KEYCODE_STAR	 ; line 58
Global $KEYCODE_POUND	 ; line 59
Global $KEYCODE_DPAD_UP	 ; line 60
Global $KEYCODE_DPAD_DOWN	 ; line 61
Global $KEYCODE_DPAD_LEFT	 ; line 62
Global $KEYCODE_DPAD_RIGHT	 ; line 63
Global $KEYCODE_DPAD_CENTER	 ; line 64
Global $KEYCODE_VOLUME_UP	 ; line 65
Global $KEYCODE_VOLUME_DOWN	 ; line 66
Global $KEYCODE_POWER	 ; line 67
Global $KEYCODE_CAMERA	 ; line 68
Global $KEYCODE_CLEAR	 ; line 69
Global $KEYCODE_A	 ; line 70
Global $KEYCODE_B	 ; line 71
Global $KEYCODE_C	 ; line 72
Global $KEYCODE_D	 ; line 73
Global $KEYCODE_E	 ; line 74
Global $KEYCODE_F	 ; line 75
Global $KEYCODE_G	 ; line 76
Global $KEYCODE_H	 ; line 77
Global $KEYCODE_I	 ; line 78
Global $KEYCODE_J	 ; line 79
Global $KEYCODE_K	 ; line 80
Global $KEYCODE_L	 ; line 81
Global $KEYCODE_M	 ; line 82
Global $KEYCODE_N	 ; line 83
Global $KEYCODE_O	 ; line 84
Global $KEYCODE_P	 ; line 85
Global $KEYCODE_Q	 ; line 86
Global $KEYCODE_R	 ; line 87
Global $KEYCODE_S	 ; line 88
Global $KEYCODE_T	 ; line 89
Global $KEYCODE_U	 ; line 90
Global $KEYCODE_V	 ; line 91
Global $KEYCODE_W	 ; line 92
Global $KEYCODE_X	 ; line 93
Global $KEYCODE_Y	 ; line 94
Global $KEYCODE_Z	 ; line 95
Global $KEYCODE_COMMA	 ; line 96
Global $KEYCODE_PERIOD	 ; line 97
Global $KEYCODE_ALT_LEFT	 ; line 98
Global $KEYCODE_ALT_RIGHT	 ; line 99
Global $KEYCODE_SHIFT_LEFT	 ; line 100
Global $KEYCODE_SHIFT_RIGHT	 ; line 101
Global $KEYCODE_TAB	 ; line 102
Global $KEYCODE_SPACE	 ; line 103
Global $KEYCODE_SYM	 ; line 104
Global $KEYCODE_EXPLORER	 ; line 105
Global $KEYCODE_ENVELOPE	 ; line 106
Global $KEYCODE_ENTER	 ; line 107
Global $KEYCODE_DEL	 ; line 108
Global $KEYCODE_GRAVE	 ; line 109
Global $KEYCODE_MINUS	 ; line 110
Global $KEYCODE_EQUALS	 ; line 111
Global $KEYCODE_LEFT_BRACKET	 ; line 112
Global $KEYCODE_RIGHT_BRACKET	 ; line 113
Global $KEYCODE_BACKSLASH	 ; line 114
Global $KEYCODE_SEMICOLON	 ; line 115
Global $KEYCODE_APOSTROPHE	 ; line 116
Global $KEYCODE_SLASH	 ; line 117
Global $KEYCODE_AT	 ; line 118
Global $KEYCODE_NUM	 ; line 119
Global $KEYCODE_HEADSETHOOK	 ; line 120
Global $KEYCODE_FOCUS	 ; line 121
Global $KEYCODE_PLUS	 ; line 122
Global $KEYCODE_MENU	 ; line 123
Global $KEYCODE_NOTIFICATION	 ; line 124
Global $KEYCODE_SEARCH	 ; line 125
Global $KEYCODE_MEDIA_PLAY_PAUSE	 ; line 126
Global $KEYCODE_MEDIA_STOP	 ; line 127
Global $KEYCODE_MEDIA_NEXT	 ; line 128
Global $KEYCODE_MEDIA_PREVIOUS	 ; line 129
Global $KEYCODE_MEDIA_REWIND	 ; line 130
Global $KEYCODE_MEDIA_FAST_FORWARD	 ; line 131
Global $KEYCODE_MUTE	 ; line 132
Global $KEYCODE_PAGE_UP	 ; line 133
Global $KEYCODE_PAGE_DOWN	 ; line 134
Global $KEYCODE_PICTSYMBOLS	 ; line 135
Global $KEYCODE_SWITCH_CHARSET	 ; line 136
Global $KEYCODE_BUTTON_A	 ; line 137
Global $KEYCODE_BUTTON_B	 ; line 138
Global $KEYCODE_BUTTON_C	 ; line 139
Global $KEYCODE_BUTTON_X	 ; line 140
Global $KEYCODE_BUTTON_Y	 ; line 141
Global $KEYCODE_BUTTON_Z	 ; line 142
Global $KEYCODE_BUTTON_L1	 ; line 143
Global $KEYCODE_BUTTON_R1	 ; line 144
Global $KEYCODE_BUTTON_L2	 ; line 145
Global $KEYCODE_BUTTON_R2	 ; line 146
Global $KEYCODE_BUTTON_THUMBL	 ; line 147
Global $KEYCODE_BUTTON_THUMBR	 ; line 148
Global $KEYCODE_BUTTON_START	 ; line 149
Global $KEYCODE_BUTTON_SELECT	 ; line 150
Global $KEYCODE_BUTTON_MODE	 ; line 151
Global $KEYCODE_ESCAPE	 ; line 152
Global $KEYCODE_FORWARD_DEL	 ; line 153
Global $KEYCODE_CTRL_LEFT	 ; line 154
Global $KEYCODE_CTRL_RIGHT	 ; line 155
Global $KEYCODE_CAPS_LOCK	 ; line 156
Global $KEYCODE_SCROLL_LOCK	 ; line 157
Global $KEYCODE_META_LEFT	 ; line 158
Global $KEYCODE_META_RIGHT	 ; line 159
Global $KEYCODE_FUNCTION	 ; line 160
Global $KEYCODE_SYSRQ	 ; line 161
Global $KEYCODE_BREAK	 ; line 162
Global $KEYCODE_MOVE_HOME	 ; line 163
Global $KEYCODE_MOVE_END	 ; line 164
Global $KEYCODE_INSERT	 ; line 165
Global $KEYCODE_FORWARD	 ; line 166
Global $KEYCODE_MEDIA_PLAY	 ; line 167
Global $KEYCODE_MEDIA_PAUSE	 ; line 168
Global $KEYCODE_MEDIA_CLOSE	 ; line 169
Global $KEYCODE_MEDIA_EJECT	 ; line 170
Global $KEYCODE_MEDIA_RECORD	 ; line 171
Global $KEYCODE_F1	 ; line 172
Global $KEYCODE_F2	 ; line 173
Global $KEYCODE_F3	 ; line 174
Global $KEYCODE_F4	 ; line 175
Global $KEYCODE_F5	 ; line 176
Global $KEYCODE_F6	 ; line 177
Global $KEYCODE_F7	 ; line 178
Global $KEYCODE_F8	 ; line 179
Global $KEYCODE_F9	 ; line 180
Global $KEYCODE_F10	 ; line 181
Global $KEYCODE_F11	 ; line 182
Global $KEYCODE_F12	 ; line 183
Global $KEYCODE_NUM_LOCK	 ; line 184
Global $KEYCODE_NUMPAD_0	 ; line 185
Global $KEYCODE_NUMPAD_1	 ; line 186
Global $KEYCODE_NUMPAD_2	 ; line 187
Global $KEYCODE_NUMPAD_3	 ; line 188
Global $KEYCODE_NUMPAD_4	 ; line 189
Global $KEYCODE_NUMPAD_5	 ; line 190
Global $KEYCODE_NUMPAD_6	 ; line 191
Global $KEYCODE_NUMPAD_7	 ; line 192
Global $KEYCODE_NUMPAD_8	 ; line 193
Global $KEYCODE_NUMPAD_9	 ; line 194
Global $KEYCODE_NUMPAD_DIVIDE	 ; line 195
Global $KEYCODE_NUMPAD_MULTIPLY	 ; line 196
Global $KEYCODE_NUMPAD_SUBTRACT	 ; line 197
Global $KEYCODE_NUMPAD_ADD	 ; line 198
Global $KEYCODE_NUMPAD_DOT	 ; line 199
Global $KEYCODE_NUMPAD_COMMA	 ; line 200
Global $KEYCODE_NUMPAD_ENTER	 ; line 201
Global $KEYCODE_NUMPAD_EQUALS	 ; line 202
Global $KEYCODE_NUMPAD_LEFT_PAREN	 ; line 203
Global $KEYCODE_NUMPAD_RIGHT_PAREN	 ; line 204
Global $KEYCODE_VOLUME_MUTE	 ; line 205
Global $KEYCODE_INFO	 ; line 206
Global $KEYCODE_CHANNEL_UP	 ; line 207
Global $KEYCODE_CHANNEL_DOWN	 ; line 208
Global $KEYCODE_ZOOM_IN	 ; line 209
Global $KEYCODE_ZOOM_OUT	 ; line 210
Global $KEYCODE_TV	 ; line 211
Global $KEYCODE_WINDOW	 ; line 212
Global $KEYCODE_GUIDE	 ; line 213
Global $KEYCODE_DVR	 ; line 214
Global $KEYCODE_BOOKMARK	 ; line 215
Global $KEYCODE_CAPTIONS	 ; line 216
Global $KEYCODE_SETTINGS	 ; line 217
Global $KEYCODE_TV_POWER	 ; line 218
Global $KEYCODE_TV_INPUT	 ; line 219
Global $KEYCODE_STB_POWER	 ; line 220
Global $KEYCODE_STB_INPUT	 ; line 221
Global $KEYCODE_AVR_POWER	 ; line 222
Global $KEYCODE_AVR_INPUT	 ; line 223
Global $KEYCODE_PROG_RED	 ; line 224
Global $KEYCODE_PROG_GREEN	 ; line 225
Global $KEYCODE_PROG_YELLOW	 ; line 226
Global $KEYCODE_PROG_BLUE	 ; line 227
Global $KEYCODE_APP_SWITCH	 ; line 228
Global $KEYCODE_BUTTON_1	 ; line 229
Global $KEYCODE_BUTTON_2	 ; line 230
Global $KEYCODE_BUTTON_3	 ; line 231
Global $KEYCODE_BUTTON_4	 ; line 232
Global $KEYCODE_BUTTON_5	 ; line 233
Global $KEYCODE_BUTTON_6	 ; line 234
Global $KEYCODE_BUTTON_7	 ; line 235
Global $KEYCODE_BUTTON_8	 ; line 236
Global $KEYCODE_BUTTON_9	 ; line 237
Global $KEYCODE_BUTTON_10	 ; line 238
Global $KEYCODE_BUTTON_11	 ; line 239
Global $KEYCODE_BUTTON_12	 ; line 240
Global $KEYCODE_BUTTON_13	 ; line 241
Global $KEYCODE_BUTTON_14	 ; line 242
Global $KEYCODE_BUTTON_15	 ; line 243
Global $KEYCODE_BUTTON_16	 ; line 244
Global $KEYCODE_LANGUAGE_SWITCH	 ; line 245
Global $KEYCODE_MANNER_MODE	 ; line 246
Global $KEYCODE_3D_MODE	 ; line 247
Global $KEYCODE_CONTACTS	 ; line 248
Global $KEYCODE_CALENDAR	 ; line 249
Global $KEYCODE_MUSIC	 ; line 250
Global $KEYCODE_CALCULATOR	 ; line 251
Global $KEYCODE_ZENKAKU_HANKAKU	 ; line 252
Global $KEYCODE_EISU	 ; line 253
Global $KEYCODE_MUHENKAN	 ; line 254
Global $KEYCODE_HENKAN	 ; line 255
Global $KEYCODE_KATAKANA_HIRAGANA	 ; line 256
Global $KEYCODE_YEN	 ; line 257
Global $KEYCODE_RO	 ; line 258
Global $KEYCODE_KANA	 ; line 259
Global $KEYCODE_ASSIST	 ; line 260
Global $KEYCODE_BRIGHTNESS_DOWN	 ; line 261
Global $KEYCODE_BRIGHTNESS_UP	 ; line 262
Global $KEYCODE_MEDIA_AUDIO_TRACK	 ; line 263
Global $SCREEN_ON_BIT	 ; line 265
Global $AIRPLANE_MODE_ON	 ; line 267
Global $ENV_EXTERNAL_STORAGE	 ; line 269
Global $ENV_SECONDARY_STORAGE	 ; line 270
Global $BATTERY_PLUGGED_AC	 ; line 272
Global $BATTERY_PLUGGED_USB	 ; line 273
Global $BATTERY_PLUGGED_WIRELESS	 ; line 274
Global $BATTERY_STATUS_UNKNOWN	 ; line 276
Global $BATTERY_STATUS_CHARGING	 ; line 277
Global $BATTERY_STATUS_DISCHARGING	 ; line 278
Global $BATTERY_STATUS_NOT_CHARGING	 ; line 279
Global $BATTERY_STATUS_FULL	 ; line 280
Global $BATTERY_HEALTH_UNKNOWN	 ; line 282
Global $BATTERY_HEALTH_GOOD	 ; line 283
Global $BATTERY_HEALTH_OVERHEAT	 ; line 284
Global $BATTERY_HEALTH_DEAD	 ; line 285
Global $BATTERY_HEALTH_OVER_VOLTAGE	 ; line 286
Global $BATTERY_HEALTH_UNSPECIFIED_FAILURE	 ; line 287
Global $BATTERY_HEALTH_COLD	 ; line 288
Global $LOW_BATTERY_THRESHOLD	 ; line 290
Global $PROPERTY_OPERATOR_NUMERIC	 ; line 292
Global $PROPERTY_OPERATOR_ALPHA	 ; line 293
Global $PROPERTY_OPERATOR_ISO_COUNTRY	 ; line 294
Global $PROPERTY_OPERATOR_ISROAMING	 ; line 295
Global $PROPERTY_DATA_NETWORK_TYPE	 ; line 296
Global $CURRENT_ACTIVE_PHONE	 ; line 297
Global $PROPERTY_SIM_STATE	 ; line 298
Global $PROPERTY_ICC_OPERATOR_NUMERIC	 ; line 299
Global $PROPERTY_ICC_OPERATOR_ALPHA	 ; line 300
Global $PROPERTY_ICC_OPERATOR_ISO_COUNTRY	 ; line 301
Global $NETWORK_TYPE_UNKNOWN	 ; line 303
Global $NETWORK_TYPE_GPRS	 ; line 304
Global $NETWORK_TYPE_EDGE	 ; line 305
Global $NETWORK_TYPE_UMTS	 ; line 306
Global $NETWORK_TYPE_CDMA	 ; line 307
Global $NETWORK_TYPE_EVDO_0	 ; line 308
Global $NETWORK_TYPE_EVDO_A	 ; line 309
Global $NETWORK_TYPE_1xRTT	 ; line 310
Global $NETWORK_TYPE_HSDPA	 ; line 311
Global $NETWORK_TYPE_HSUPA	 ; line 312
Global $NETWORK_TYPE_HSPA	 ; line 313
Global $NETWORK_TYPE_IDEN	 ; line 314
Global $NETWORK_TYPE_EVDO_B	 ; line 315
Global $NETWORK_TYPE_LTE	 ; line 316
Global $NETWORK_TYPE_EHRPD	 ; line 317
Global $NETWORK_TYPE_HSPAP	 ; line 318
Global $NETWORK_CLASS_UNKNOWN	 ; line 320
Global $NETWORK_CLASS_2_G	 ; line 321
Global $NETWORK_CLASS_3_G	 ; line 322
Global $NETWORK_CLASS_4_G	 ; line 323
Global $PHONE_TYPE_NONE	 ; line 325
Global $PHONE_TYPE_GSM	 ; line 326
Global $PHONE_TYPE_CDMA	 ; line 327
Global $PHONE_TYPE_SIP	 ; line 328
Global $SIM_STATE_UNKNOWN	 ; line 330
Global $SIM_STATE_ABSENT	 ; line 331
Global $SIM_STATE_PIN_REQUIRED	 ; line 332
Global $SIM_STATE_PUK_REQUIRED	 ; line 333
Global $SIM_STATE_NETWORK_LOCKED	 ; line 334
Global $SIM_STATE_READY	 ; line 335

; Source file: C:\Users\Kyaw Swar Thwin\Desktop\Huawei Hacker Toolkit\AES.au3
Global $_AES_CodeBuffer	 ; line 10
Global $_AES_CodeBufferMemory	 ; line 10
Global $_AES_EncryptOffset	 ; line 11
Global $_AES_DecryptOffset	 ; line 11
Global $_AES_EncryptKeyOffset	 ; line 11
Global $_AES_DecryptKeyOffset	 ; line 11
Global $_AES_EncryptECBOffset	 ; line 12
Global $_AES_DecryptECBOffset	 ; line 12
Global $_AES_EncryptCBCOffset	 ; line 13
Global $_AES_DecryptCBCOffset	 ; line 13
Global $_AES_EncryptCFBOffset	 ; line 14
Global $_AES_DecryptCFBOffset	 ; line 14
Global $_AES_CryptOFBOffset	 ; line 15
Global $_AES_ModeResetOffset	 ; line 15
Global $AES_CBC_MODE	 ; line 16
Global $AES_CFB_MODE	 ; line 16
Global $AES_OFB_MODE	 ; line 16
